default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: english_note_development
  host: localhost
  username: postgres
  password: postgres
test:
  <<: *default
  database: english_note_test
  host: localhost
  username: postgres
  password: postgres
production:
  <<: *default
  host: <%= ENV["DATABASE_URL"] %>
  database: english_note_production
  username: english_note
